# Generated by Django 2.2.5 on 2019-11-20 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_debt_expense_income_investment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='payed_by',
        ),
        migrations.RemoveField(
            model_name='income',
            name='payed_to',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='investor',
        ),
        migrations.DeleteModel(
            name='Debt',
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
        migrations.DeleteModel(
            name='Income',
        ),
        migrations.DeleteModel(
            name='Investment',
        ),
    ]
