# Generated by Django 2.2.5 on 2019-11-20 20:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boards', '0004_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionID', models.CharField(max_length=10, unique=True)),
                ('amount_inv', models.FloatField()),
                ('amount_returned', models.FloatField()),
                ('date_acquired', models.DateField()),
                ('date_payed', models.DateField(null=True)),
                ('investor', models.ForeignKey(on_delete='CASCADE', related_name='investments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionID', models.CharField(max_length=10, unique=True)),
                ('amount', models.FloatField()),
                ('inType', models.CharField(max_length=15)),
                ('date_earned', models.DateField()),
                ('year_earned', models.IntegerField()),
                ('payed_to', models.ForeignKey(on_delete='CASCADE', related_name='incomes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionID', models.CharField(max_length=10, unique=True)),
                ('amount', models.FloatField()),
                ('date_earned', models.DateField()),
                ('year_earned', models.IntegerField()),
                ('payed_by', models.ForeignKey(on_delete='CASCADE', related_name='expenses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionID', models.CharField(max_length=10, unique=True)),
                ('amount', models.FloatField()),
                ('intrest', models.FloatField()),
                ('date_acquired', models.DateField()),
                ('date_payed', models.DateField(null=True)),
                ('debtor', models.ForeignKey(on_delete='CASCADE', related_name='debts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
