# Generated by Django 2.2.5 on 2019-11-21 00:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boards', '0005_debt_expense_income_investment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('board', models.ForeignKey(on_delete='CASCADE', related_name='topics', to='boards.Board')),
                ('starter', models.ForeignKey(on_delete='CASCADE', related_name='topics', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
