# Generated by Django 2.2.5 on 2019-11-24 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0006_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='exType',
            field=models.CharField(default='Other', max_length=20),
            preserve_default=False,
        ),
    ]
