# Generated by Django 2.2.5 on 2019-11-25 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0007_expense_extype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='date_earned',
            new_name='date_spent',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='year_earned',
            new_name='year_spent',
        ),
    ]
