# Generated by Django 2.2.5 on 2019-11-25 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0008_auto_20191124_2143'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
