# Generated by Django 2.2.5 on 2019-11-29 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0009_delete_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debt',
            name='date_payed',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='date_payed',
        ),
        migrations.AddField(
            model_name='debt',
            name='year_payed',
            field=models.IntegerField(default=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investment',
            name='year_payed',
            field=models.IntegerField(default=2000),
            preserve_default=False,
        ),
    ]
